/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import OperacoesPackage.Operacoes;
import PrologPackage.PrologFile;
import PrologPackage.PrologInterpreter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.AbstractButton;
import javax.swing.ButtonModel;

/**
 *
 * @author Doug
 */
public class MontarOperacao extends javax.swing.JFrame {

    private Operacoes operacao;
    /**
     * Creates new form MontarOperacao
     */
    public MontarOperacao() {
        operacao = new Operacoes();
        initComponents();
        txtId.setText(""+operacao.getIdOperacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txtId = new javax.swing.JTextField();
        txtNameOperacao = new javax.swing.JTextField();
        TxtResponsavel = new javax.swing.JTextField();
        txtLocalidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboAtiradorElite = new javax.swing.JCheckBox();
        cboSoldadoElite = new javax.swing.JCheckBox();
        cboHelicoptero = new javax.swing.JCheckBox();
        cboAviao = new javax.swing.JCheckBox();
        cboTripulacao = new javax.swing.JCheckBox();
        cboCarga = new javax.swing.JCheckBox();
        cboInfantaria = new javax.swing.JCheckBox();
        cboSigilo = new javax.swing.JCheckBox();
        cboChuva = new javax.swing.JCheckBox();
        cboNeve = new javax.swing.JCheckBox();
        cboAereo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cboAgua = new javax.swing.JCheckBox();
        cboTerra = new javax.swing.JCheckBox();
        cboDeserto = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtNameOperacao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtResponsavel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtLocalidade.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome da Operacao:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Responsável:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Localidade:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Operações");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton1.setText("Fácil");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton2.setText("Médio");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadioButton3.setText("Díficil");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dificuldade:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Requisitos:");

        buttonGroup2.add(cboAtiradorElite);
        cboAtiradorElite.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboAtiradorElite.setText("Atirador de Elite");

        buttonGroup2.add(cboSoldadoElite);
        cboSoldadoElite.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboSoldadoElite.setText("Soldado De Elite");

        buttonGroup2.add(cboHelicoptero);
        cboHelicoptero.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboHelicoptero.setText("Helicóptero");

        buttonGroup2.add(cboAviao);
        cboAviao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboAviao.setText("Avião");

        buttonGroup2.add(cboTripulacao);
        cboTripulacao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboTripulacao.setText("Transporte de Tripulação");

        buttonGroup2.add(cboCarga);
        cboCarga.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboCarga.setText("Transporte de Carga");

        buttonGroup2.add(cboInfantaria);
        cboInfantaria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboInfantaria.setText("Infantaria");

        buttonGroup2.add(cboSigilo);
        cboSigilo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboSigilo.setText("Operação Sigilosa");

        buttonGroup3.add(cboChuva);
        cboChuva.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboChuva.setText("Chuva");

        buttonGroup3.add(cboNeve);
        cboNeve.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboNeve.setText("Neve");

        buttonGroup3.add(cboAereo);
        cboAereo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboAereo.setText("Áereo");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Terreno:");

        buttonGroup3.add(cboAgua);
        cboAgua.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboAgua.setText("Água");

        buttonGroup3.add(cboTerra);
        cboTerra.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboTerra.setText("Terra");

        buttonGroup3.add(cboDeserto);
        cboDeserto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cboDeserto.setText("Deserto");

        btnOk.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnOk.setText("Selecionar Esquadrão");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TxtResponsavel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNameOperacao, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLocalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSoldadoElite)
                                    .addComponent(cboHelicoptero)
                                    .addComponent(cboAtiradorElite)
                                    .addComponent(cboAviao)
                                    .addComponent(cboTerra)
                                    .addComponent(cboAereo)
                                    .addComponent(cboAgua))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboChuva)
                                    .addComponent(cboDeserto)
                                    .addComponent(cboNeve)
                                    .addComponent(cboSigilo)
                                    .addComponent(cboTripulacao)
                                    .addComponent(cboInfantaria)
                                    .addComponent(cboCarga)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAtiradorElite)
                    .addComponent(cboTripulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSoldadoElite)
                    .addComponent(cboCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHelicoptero)
                    .addComponent(cboInfantaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAviao)
                    .addComponent(cboSigilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAgua)
                    .addComponent(cboChuva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTerra)
                    .addComponent(cboNeve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAereo)
                    .addComponent(cboDeserto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        operacao.setDificuldade(buttonGroup1.getElements().nextElement().getText());
        operacao.setLocalidade(txtLocalidade.getText());
        operacao.setNomeOperacao(txtNameOperacao.getText());
        operacao.setResponsavel(TxtResponsavel.getText());
        operacao.setRequisitos(getRequisitos());
        operacao.setTerreno(getTerrenos());
        
        PrologFile prolog = new PrologFile("src\\zMisc\\PrologFiles\\soldados.pro");
        try {
            prolog.escreverRegras();
        } catch (IOException ex) {
            Logger.getLogger(MontarOperacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        gerarXMLProlog(prolog);
    }//GEN-LAST:event_btnOkActionPerformed

    private ArrayList getRequisitos()
    {
        ArrayList botoes = null;
        AbstractButton botao;
        boolean add = false;
        
        //for (Enumeration<E> e = v.elements(); e.hasMoreElements();)
        for (Enumeration e  = buttonGroup2.getElements(); e.hasMoreElements();)
        {
            botao = (AbstractButton) e.nextElement();
            if (botao.isSelected())
            {
               add  = botoes.add(botao.getText());
            }
        }
        if (add == true)
            return botoes;
        return null;
    }
    
    private ArrayList getTerrenos()
    {
        ArrayList botoes = null;
        AbstractButton botao;
        boolean add = false;
       for (Enumeration e  = buttonGroup2.getElements(); e.hasMoreElements();)
        {
            botao = (AbstractButton) e.nextElement();
            if (botao.isSelected())
            {
               add  = botoes.add(botao.getText());
            }
        }
        if (add == true)
            return botoes;
        return null;
    }
     private void gerarXMLProlog(PrologFile prolog) {
         int numeroSoldados=0;
         switch (operacao.getDificuldade()){
             case "Díficil": numeroSoldados = 7;
                 break;
             case "Médio": numeroSoldados=3;
                 break;
             case "Fácio": numeroSoldados=1;
                 break;
             default: numeroSoldados=-1;
         }
         
         try {
            prolog.escritorArquivo("numeroSoldados(X, Y):-proper_lenght(X,Y)"
                    + ".");

            prolog.escritorArquivo("adcionaSoldado(Xlist, Yrequisito):-append(Xlist, requisitos(Z,Yrequisito),Xlist).");
            prolog.escritorArquivo("percorreSoldados(Ysoldado,Xlist,0):-nth0(0,Xlist,Ysoldado)!.");
            prolog.escritorArquivo("percorreSoldados(Ysoldado,Xlist,Znumero):-"
                    + "percorreSoldados(Ysoldado,Xlist,Znumero-1)"
                    + "nth0(Znumero,Xlist,K)"
                    + ".");
            PrologPackage.PrologInterpreter intw = new PrologInterpreter("adcionaSoldado(X, '"+ operacao.getRequisitos().get(0) + "').");
            
             Hashtable[] hash = intw.todasSolucoes(intw.getExecutor());
            prolog.escritorArquivo("criaXML(ARQ,ZnumeroSoldados):-"
                    + "tell(ARQ)"
                    + "write('<OPERACAO id=+"+ operacao.getIdOperacao()+ ">'), nl,"
                    + "write('<SOLDADO>', percorreSoldados(Y, ["
                    + ""
                    + ""
                    + ".");
        } catch (IOException ex) {
            Logger.getLogger(MontarOperacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtResponsavel;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cboAereo;
    private javax.swing.JCheckBox cboAgua;
    private javax.swing.JCheckBox cboAtiradorElite;
    private javax.swing.JCheckBox cboAviao;
    private javax.swing.JCheckBox cboCarga;
    private javax.swing.JCheckBox cboChuva;
    private javax.swing.JCheckBox cboDeserto;
    private javax.swing.JCheckBox cboHelicoptero;
    private javax.swing.JCheckBox cboInfantaria;
    private javax.swing.JCheckBox cboNeve;
    private javax.swing.JCheckBox cboSigilo;
    private javax.swing.JCheckBox cboSoldadoElite;
    private javax.swing.JCheckBox cboTerra;
    private javax.swing.JCheckBox cboTripulacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtNameOperacao;
    // End of variables declaration//GEN-END:variables

   
}
